services:
  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ports:
      - 1865:80
      - 5678:5678
    volumes:
      - ./cat/static:/app/cat/static
      - ./cat/plugins:/app/cat/plugins
      - ../kibana-api/kibcat_api.py:/app/cat/plugins/kibcat/utils/kibcat_api.py
      - ../logger/base_logger.py:/app/cat/plugins/kibcat/utils/base_logger.py
      - ./cat/data:/app/cat/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
