repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--line-length=120"]
        exclude: ^cat/

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--profile=black"]
        exclude: ^cat/

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["--config-file=mypy.ini", "--explicit-package-bases", "--namespace-packages"]
        exclude: ^cat/

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=.pylintrc", "."]
        pass_filenames: false
        exclude: ^cat/
