repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--line-length=120"]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--profile=black"]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["--config-file=mypy.ini", "--explicit-package-bases", "--namespace-packages"]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
