services:
  cheshire-cat-core:
    build:
      context: ./cc_docker_image
      dockerfile: Dockerfile
    container_name: cheshire_cat_core
    extra_hosts:
      - "${ELASTIC_URL_PRIVATE}:${IP_PRIVATE}"
      - "${KIBANA_URL_PRIVATE}:${IP_PRIVATE}"
    ports:
      - 1865:80
      - 5678:5678
      - 443:443
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/cat/plugins/kibcat/imports
    volumes:
      # Cheshire Cat
      - ./cat/static:/app/cat/static
      - ./cat/plugins:/app/cat/plugins
      - ./cat/data:/app/cat/data
      # SRC to imports
      - ./src:/app/cat/plugins/kibcat/imports
      # Requirements
      - ./requirements.txt:/app/cat/plugins/kibcat/requirements.txt
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
