[tool.black]
line-length = 120
target-version = ['py310']
exclude = '/(venv|\.git)/'

[tool.isort]
profile = "black"
line_length = 120
skip = ["venv", ".git"]
src_paths = ["src", "tests", "examples", "cat/plugins/kibcat"]

